spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  config:
    activate:
      on-profile: sso

#          microsoft:
#            client-id: ${OAUTH2_MICROSOFT_CLIENT_ID:}
#            client-secret: ${OAUTH2_MICROSOFT_CLIENT_SECRET:}
#            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - email
#              - profile
#              - openid
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#        provider:
#          microsoft:
#            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: email

app:
  oauth2:
    # Redirect URLs after successful/failed authentication
    success-redirect-url: ${PUBLIC_FRONT_URL}/oauth2/success
    failure-redirect-url: ${PUBLIC_FRONT_URL}/oauth2/failure